website/auth.py
from flask import Blueprint,render_template,request,redirect,url_for,after_this_request
from website import db_connect
from psycopg2 import IntegrityError
from datetime import datetime,timedelta


auth = Blueprint('auth',__name__)


@auth.route("/")
@auth.route("/<typ>",methods = ['GET','POST'])
def authenticate(typ='log'):
    if request.method == 'POST':
        conn = db_connect()
        cur = conn.cursor()
        if typ == 'log':
            mail = request.form.get("email")
            pwd = request.form.get("password")
            print(mail,pwd)
            cur.execute("SELECT pwd,name,user_access_id,id FROM user_auth WHERE mail = %s",(mail,))
            db_data = cur.fetchall()
            db_pwd = db_data[0][0] if db_data != [] else None
            print(pwd,db_pwd)
            if db_pwd == pwd:
                @after_this_request
                def after_index(response):
                    response.set_cookie("cpu_username",db_data[0][1],expires=datetime.now() + timedelta(seconds=10))
                    response.set_cookie("cpu_role",str(db_data[0][2]),expires=datetime.now() + timedelta(seconds=10))
                    response.set_cookie("cpu_user_id",str(db_data[0][3]),expires=datetime.now() + timedelta(seconds=10))
                    return response
                return redirect(url_for('views.home'))
            else:
                return render_template('auth.html',mgs='အီးမေးလ် (သို့) စကားဝှက် မှားယွင်းနေပါသည်။ ',typ='log')
        else:
            name = request.form.get("username")
            mail = request.form.get("email")
            pwd = request.form.get("password")
            confirmPwd = request.form.get("confirmPassword")
            print(name,mail,pwd,confirmPwd)
            if typ == 'reg':
                if pwd == confirmPwd:
                    try:
                        cur.execute("INSERT INTO user_auth (name,mail,pwd,user_access_id) VALUES (%s,%s,%s,5)",(name,mail,pwd))
                        conn.commit()
                        return redirect(url_for('auth.authenticate',typ='log'))
                    except IntegrityError as err:
                        print(err)
                        return render_template('auth.html',mgs='ဤအီးမေလ် ဖြင့် အကောင့် ပြုလုပ်ထားခြင်း ရှိပါသည်',typ='reg')
                else:
                    return render_template('auth.html',mgs='စကားဝှက် နှင့် အတည်ပြု စကားဝှက်သည် ကိုက်ညီမှု မရှိပါ။',typ='reg')
            elif typ == 'forgot':
                cur.execute("SELECT name FROM user_auth WHERE mail = %s",(mail,))
                data = cur.fetchall()
                db_name = data[0][0] if data != [] else None
                if db_name == name:
                    if pwd == confirmPwd:
                        cur.execute("UPDATE user_auth SET pwd = %s WHERE mail = %s;",(pwd,mail))
                        conn.commit()
                        return redirect(url_for('auth.authenticate',typ='log'))
                    else:
                        return render_template('auth.html',mgs='စကားဝှက် နှင့် အတည်ပြု စကားဝှက်သည် ကိုက်ညီမှု မရှိပါ။',typ='forgot')
                else:
                    return render_template('auth.html',mgs='အီးမေးလ် (သို့) စကားဝှက် မှားယွင်းနေပါသည်။',typ='forgot')
    else:
        return render_template('auth.html',typ=typ,mgs=None)

@auth.route("logout")
def logout():
    return redirect(url_for('auth.authenticate'))

@auth.route("checkforget/<email>/<name>")
def checkforget(name,email):
    conn = db_connect()
    cur = conn.cursor()
    cur.execute("SELECT name FROM user_auth WHERE mail = %s;",(email,))
    db_data = cur.fetchall()
    db_name = db_data[0][0] if db_data != [] else None
    if db_name == name:
        return [1]
    else:
        return [0]

@auth.route("/admin/<mgs>",methods=['GET','POST']) 
@auth.route("/admin",methods=['GET','POST'])
def admin_panel(mgs=None):
    conn = db_connect()
    cur = conn.cursor()
    role = request.cookies.get('cpu_role')
    user_id = request.cookies.get("cpu_user_id")
    if not role:
        return redirect(url_for('views.home'))
    else:
        if role != '4':
            return render_template('access_error.html')
    if request.method == 'POST':
        user_id = request.form.get("income_expense_id")
        cur.execute("SELECT users.id,users.name,users.mail,access.name,access.id FROM user_auth AS users LEFT JOIN user_access access ON users.user_access_id = access.id WHERE users.id = %s;",(user_id,))
        user_data = cur.fetchone()
        cur.execute("SELECT id,code,name FROM analytic_project_code")
        pj_datas = cur.fetchall()
        cur.execute("SELECT id,name FROM user_access;")
        access_datas = cur.fetchall()
        cur.execute("SELECT pj.id,pj.code,pj.name FROM analytic_project_code AS pj;")
        project_datas = cur.fetchall()
        if user_data[4] == 4:
<<<<<<< HEAD
            user_projects = project_datas
        else:
            cur.execute("SELECT pj.id,pj.code,pj.name FROM project_user_access access LEFT JOIN  analytic_project_code pj ON access.project_id = pj.id WHERE access.user_id = %s;",(user_id,))
            user_projects = cur.fetchall()
        return render_template('admin_panel.html',not_tree=True,user_data=user_data,pj_datas=pj_datas,access_datas=access_datas,project_datas=project_datas,user_projects=user_projects)
=======
            user_own_projects = project_datas
        else:
            cur.execute("SELECT pj.id,pj.code,pj.name FROM project_user_access access LEFT JOIN  analytic_project_code pj ON access.project_id = pj.id WHERE access.user_id = %s;",(user_id,))
            user_own_projects = cur.fetchall()
        print(user_data)
        return render_template('admin_panel.html',not_tree=True,user_data=user_data,pj_datas=pj_datas,access_datas=access_datas,project_datas=project_datas,user_own_projects=user_own_projects)
>>>>>>> bee687fdb11b034dc03d88b274efa657a66b13a2
    else:
        cur.execute("SELECT id,name,mail FROM user_auth ORDER BY name LIMIT 81;")
        all_users = cur.fetchall()
        cur.execute("SELECT count(*) FROM user_auth;")
        all_users_count = cur.fetchone()[0]
        cur.execute("SELECT pj.id,code,name FROM analytic_project_code AS pj;")
        project_datas = cur.fetchall()
    
    return render_template("admin_panel.html",all_users=all_users,total=all_users_count,project_datas=project_datas,mgs=mgs)

@auth.route("/add-remove-projects/<typ>",methods=['POST'])
def add_remove_pj(typ):
    if request.method == 'POST':
        conn = db_connect()
        cur = conn.cursor()
        project_ids = request.form.get("project_ids")
        user_id = request.form.get("user_id")
        current_role = request.cookies.get("cpu_role")
        if current_role != '4':
            return render_template('access_error.html')
        if typ == 'add':
            for data in project_ids.split(","):
                cur.execute("SELECT id FROM project_user_access WHERE user_id = %s AND project_id = %s;",(user_id,data))
                if not cur.fetchone():
                    cur.execute("INSERT INTO project_user_access(user_id,project_id) VALUES(%s,%s);",(user_id,data))
        elif typ == 'remove':
            cur.execute("DELETE FROM project_user_access WHERE user_id = %s AND project_id IN %s;",(user_id,tuple(project_ids.split(','))))
        cur.execute("SELECT users.id,users.name,users.mail,access.name FROM user_auth AS users LEFT JOIN user_access access ON users.user_access_id = access.id WHERE users.id = %s;",(user_id,))
        user_data = cur.fetchone()
        cur.execute("SELECT id,code,name FROM analytic_project_code")
        pj_datas = cur.fetchall()
        cur.execute("SELECT id,name FROM user_access;")
<<<<<<< HEAD
        access_datas = cur.fetchall()
=======
        access_datas = cur.fetchall()        
        cur.execute("SELECT pj.id,pj.code,pj.name FROM project_user_access access LEFT JOIN  analytic_project_code pj ON access.project_id = pj.id WHERE access.user_id = %s;",(user_id,))
        user_own_projects = cur.fetchall()
        print(user_own_projects)
>>>>>>> bee687fdb11b034dc03d88b274efa657a66b13a2
        if current_role != '4':
            return render_template("access_error.html")
        cur.execute("SELECT pj.id,pj.code,pj.name FROM analytic_project_code AS pj;")
        project_datas = cur.fetchall()
        cur.execute("SELECT pj.id,pj.code,pj.name FROM project_user_access access LEFT JOIN  analytic_project_code pj ON access.project_id = pj.id WHERE access.user_id = %s;",(user_id,))
<<<<<<< HEAD
        user_projects = cur.fetchall()
        conn.commit()
        cur.close()
        conn.close()
        return render_template('admin_panel.html',not_tree=True,user_data=user_data,pj_datas=pj_datas,access_datas=access_datas,project_datas=project_datas,user_projects = user_projects)
=======
        user_own_projects = cur.fetchall()
        conn.commit()
        cur.close()
        conn.close()
        return render_template('admin_panel.html',not_tree=True,user_data=user_data,pj_datas=pj_datas,access_datas=access_datas,project_datas=project_datas,user_own_projects=user_own_projects)
>>>>>>> bee687fdb11b034dc03d88b274efa657a66b13a2

@auth.route("/change-user-access",methods=['POST'])
def change_user_access():
    if request.method == 'POST':
        conn = db_connect()
        cur = conn.cursor()
        current_user_id = request.cookies.get("cpu_user_id")
        user_id = request.form.get("user_id")
        current_role = request.cookies.get("cpu_role")
        if current_role != '4':
            return render_template('access_error.html')
        access_id = request.form.get("access_id")
        cur.execute("UPDATE user_auth SET user_access_id = %s WHERE id = %s;",(access_id,user_id))
        conn.commit()
        cur.close()
        conn.close()
        @after_this_request
        def after_index(response):
            if user_id == current_user_id:

website/templates/access_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthroized Access</title>
    <style>
        html { box-sizing: border-box; }

        *,
        *::before,
        *::after { box-sizing: inherit; }

        body * {
        margin: 0;
        padding: 0;
        }

        body {
        font: normal 100%/1.15 "Merriweather", serif;
        background: #fff url("../static/images/texture.jpg") repeat 0 0;
        color: #fff;
        }

        .wrapper {
        position: relative;
        max-width: 1298px;
        height: auto;
        margin: 2em auto 0 auto;
        background: transparent url("../static/images/wood-fence.png") no-repeat center top 24em;
        }

        /* https://www.vecteezy.com/vector-art/237238-dog-family-colored-doodle-drawing */
        .box {
        max-width: 70%;
        min-height: 600px;
        margin: 0 auto;
        margin-top: -30px;
        padding: 1em 1em;
        text-align: center;
        background: transparent url("../static/images/puppies.jpg") no-repeat top 10em center;
        }

        h1 {
        margin: 0;
        font-size: 8em;
        text-shadow: 0 0 6px #8b4d1a;
        }

        p {
        margin-bottom: 0.5em;
        font-size: 1.75em;
        color: #ea8a1a;
        }

        p:first-of-type {
        margin-top: 16em;
        text-shadow: none;
        }

        p > a {
        border-bottom: 1px dashed #837256;
        font-style: italic;
        text-decoration: none;
        color: #837256;
        }

        p > a:hover { text-shadow: 0 0 3px #8b4d1a; }

        p img { vertical-align: bottom; }

        @media screen and (max-width: 600px) {
        .wrapper {
            background-size: 300px 114px;
            background-position: center top 22em;
            }

        .box {
            max-width: 100%;
            margin: 0 auto;
            padding: 0;
            background-size: 320px 185px;
        }

        p:first-of-type { margin-top: 12em; }
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <div class="box">
            <h1>403</h1>
            <p>Sorry, it's not allowed to go beyond this point!</p>
            <p><a href="/">Please, go back this way.</a></p>
        </div>
    </div>
</body>
</html>

website/templates/admin_panel.html
{% extends 'base.html' %}
{% block title %} Admin Panel {% endblock %}

{% block content %}

{% if not_tree %}

<form action="{{url_for('imports.delete_form')}}" hidden id="delete-form-id" method="post">
    <input type="text" value="" name="for_what" id="forWhat"/> 
    <input type="number" value="" name="delete_id" id="deleteId"/>
</form>
<div class="mt-3 ms-3">
    <a class="nav-item text-white" href="{{url_for('auth.admin_panel')}}"> 
        <button class="btn btn-secondary" type="button">မလုပ်ဆောင်တော့ပါ</button>
    </a>
    <button class="btn btn-danger" onclick="deleteFormData('{{user_data[0]}}','user_account')">အကောင့် ဖျက်ပစ်ရန်</button>     
</div>

<h1 class="text-center ms-3 py-3 adminControl" style="margin-top: -40px;">Admin Control Panel</h1>
    <div class="card w-75 mx-auto mb-3 shadow-sm rounded-0">
        <div class="card-header text-white rounded-0" style="background-color: #2C41AD;">
            User Details
        </div>
        <div class="d-flex justify-content-between p-3" id="detailCard">
            <div class="">
                <p class="card-text m-0 text-primary">Username</p>
                <h5 class="card-title">{{user_data[1]}}</h5>
                <p class="card-text m-0 text-primary">Email</p>
                <h5 class="card-title">{{user_data[2]}}</h5>
                <p class="card-text m-0 text-primary">User Role</p>
                <h5 class="card-title" id="userRoleShow">{{user_data[3]}}</h5>
            </div>
            <div class="w-50">
                <p class="card-text m-0 text-primary">Projects List</p>
                <div style="height: 150px;overflow: auto;" id="detailPrjList">
<<<<<<< HEAD
                    {% for data in user_projects %}
=======
                    {% for data in user_own_projects %}
>>>>>>> bee687fdb11b034dc03d88b274efa657a66b13a2
                        <h6 class="card-title">{{data[2]}} ( {{data[1]}} )</h6>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="w-75 mx-auto" id="inputSection">
        <div class="mb-3 shadow-sm">
            <form action="{{url_for('auth.add_remove_pj',typ='add')}}" method="post">
                <div class="input-group">
                    <input type="text" required value="" name="project_ids" id="projectAdd" hidden>
                    <input hidden type="number" id="user_id" name="user_id" value="{{user_data[0]}}"/>
                    <input class="form-control" type="text" id="inputForProjectInMonthly" size="22" autocomplete="off" onkeyup="getShopsMultiSelect(this)"/>
                    <button class="btn btn-success input-group-text" type="submit">Add Projects</button>
                    <div style="max-height: 150px;width: 80%;overflow-y: auto;display: none;position: absolute;top: 100%;z-index: 5;background-color: white;" id="aboveProjectCodesForExport">
                        <div id="projectDrop">
                            {% for data in pj_datas %}
                                <p id="{{data[0]}}" style="position: relative;margin: 0;display: flex;" onchange="addProject(this)">{{data[1]}} | {{data[2]}}<input type="checkbox" style="position: absolute;right: 5px;top: 50%;transform: translateY(-50%)"/></p>
                            {% endfor %}
                        </div>
                    </div> 
                </div>
            </form>
        </div>  
        <div class="mb-3 shadow-sm">
            <form action="{{url_for('auth.add_remove_pj',typ='remove')}}" method="post">
                <div class="input-group">
                    <input hidden type="text" required name="project_ids" value="" id="projectRemove">
                    <input hidden type="number" id="user_id" name="user_id" value="{{user_data[0]}}"/>
                    <input class="form-control" type="text" id="inputForProjectInMonthly" size="22" autocomplete="off" onkeyup="getShopsMultiSelect(this)"/>
                    <button type="submit" class="btn btn-danger">Remove Projects</button>
                    <div style="max-height: 150px;width: 80%;overflow-y: auto;display: none;position: absolute;top: 100%;z-index: 5;background-color: white;" id="aboveProjectCodesForExport">
                        <div id="projectDrop">
                            {% for data in user_projects %}
                            <p id="{{data[0]}}" style="position: relative;margin: 0;display: flex;" onchange="removeProject(this)">{{data[1]}} | {{data[2]}}<input type="checkbox" style="position: absolute;right: 5px;top: 50%;transform: translateY(-50%)"/></p>
                            {% endfor %}
                        </div>
                    </div> 
                </div>
            </form>
        </div>
        <div class="mb-5 shadow-sm">
            <form action="{{url_for('auth.change_user_access')}}" method="post">
                <div class="input-group">
                    <input hidden type="number" id="user_id" name="user_id" value="{{user_data[0]}}"/>
                    <select class="form-select" name="access_id" id="inputGroupSelect02">
                        {% for data in access_datas %}
                            <option value="{{data[0]}}">{{data[1]}}</option>
                        {% endfor %}
                    </select>
                    <button class="input-group-text btn btn-primary text-white rounded-0" type="submit" for="inputGroupSelect02" >Change User Role</button>
                </div>
            </form>
        </div>           
    </div>
</div>
{% else %}
<form id="hidden-income-expense-form" action="{{url_for('auth.admin_panel')}}" method="post">
    <input type="number" name="income_expense_id" id="hidden-income-expense-id" value="{{user_idd}}" hidden>
</form>
<h1 class="text-center m-2">Authenticated Users</h1>
<div class="text-center m-3">
    <div class="row">
        <div class="col-md-6 d-flex align-items-center">
            <form role="search">
                <div class="input-group">
                    <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                </div>
            </form>
            <button data-bs-toggle="modal" data-bs-target="#exportStaticBackdrop" onclick="setDbAndGiveProjectCodes('Income Expense Query')" class="btn btn-secondary text-white mx-2"><i class="fa-solid fa-download"></i></button>
        </div>
        <div class="col-md-6 col-sm-12 text-end mt-2">
            <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" onclick="clickPagination(this,'Income Expense Query','prev')" class="btn btn-primary">Prev</button>
                <button type="button" class="btn btn-outline-dark" disabled=""> 1- {% if total >= 81 %} 81 {% else %} {{total}} {% endif %} / {{total}}</button>
                <button type="button" onclick="clickPagination(this,'Income Expense Query','next')" class="btn btn-primary">Next</button>
            </div>
        </div>
    </div>
</div>
<div class="cpu-table-sec">
    <table>
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            {% for user in all_users %}
            <tr onclick="redirectToProjectStatForm('hidden-income-expense-id','hidden-income-expense-form','{{user[0]}}')">
                <td>{{user[1]}}</td>
                <td> {{user[2]}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endif %}
{% endblock %}

{% block project_datas %}
    {% for data in project_datas %}
        <p class="m-1 ms-2" shopid="{{data[0]}}" projectcode="{{data[1]}}" onclick="assignShop(this)">{{data[2]}} _&_ {{data[1]}}</p>
    {% endfor %}
{% endblock %}

{% block mgsContent %}{{ mgs | safe }}{% endblock %}

website/templates/daily_activities_transition.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js" integrity="sha512-uKQ39gEGiyUJl4AI6L+ekBdGKpGw4xJ55+xyJG7YFlJokPNYegn9KwQ3P8A7aFQAUtUsAQHep+d/lrGqrbPIDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="../static/styles/table.css">
    <title>Daily Activities Transition List</title>
</head>
<body>
    <h1 class="text-center">Daily Activity Transaction List</h1>
    <div class="text-center m-3">
        <div class="row">
            <div class="col d-flex">
                <form role="search">
                    <div class="input-group">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                    </div>
                </form>
                <button class="btn btn-secondary text-white ms-2"><i class="fa-solid fa-download"></i></button>
            </div>
            <div class="col text-end">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-primary">Prev</button>
                    <button type="button" class="btn btn-outline-dark" disabled> 1-81 / 14444</button>
                    <button type="button" class="btn btn-primary">Next</button>
                </div>
            </div>
        </div>
    </div>  
        <div class="table-sec">
            <table>
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Project Code</th>
                        <th>Project Name</th>
                        <th>No</th>
                        <th>Machine</th>
                        <th>Job Type</th>
                        <th>Capacity</th>
                        <th>Duty Hour</th>
                        <th>Liter</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-start">2023-09-30</td>
                        <td class="text-start">PTG-20-21-007-1</td>
                        <td class="text-wrap"
                        title="BGO-Ka Wa-A lel Ywar-Yit Kan Gyi-Thone Gwa Concrete Bridge(1) "
                        >BGO-Ka Wa-A lel Ywar-Yit Kan Gyi-Thone Gwa Concrete Bridge(1)</td>
                        <td class="text-start">မဆလာလှော်</td>
                        <td class="text-start">BudozarBudozarBudozarBudozar</td>
                        <td class="text-start">Building</td>
                        <td class="text-end">1234</td>
                        <td class="text-end">1.00</td>
                        <td class="text-end">12990</td>
                        <td class="text-wrap" 
                            title="Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
                            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, 
                            when an unknown printer took a galley of type and scrambled it to make a type specimen book
                            . It has survived not only five centuries, but also the leap into electronic typesetting, 
                            remaining essentially unchanged. It was popularised in the 1960s with the release of 
                            Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing 
                            software like Aldus PageMaker including versions of Lorem Ipsum.">
                            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
</body>
</html>

website/templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
<div class="home-page">
    <!-- banner start -->
        <div class="container-fluid shadow-sm" style="background-color: #dee3ff;" id="cmpyBanner">
            <div class="row justify-content-center align-items-center banners">
                <div class="col-md-10 text-center py-5">
                    <h1 class="display-4"><span class="fw-bold" style="color: #2C41AD;">Mudon Maung Maung</span>
                    <span class="text-primary">Co Ltd.</span></h1>
                    <h1 class="text-secondary fst-italic fw-light">Group Of Companies</h1>
                </div>
            </div>
        </div>
    <!-- banner end -->
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="" id="backgroundImage">
                <img src="../static/images/1.jpg" class="w-100" alt="...">
            </div>
            <!-- <div class="carousel-item">
                <img src="../static/images/3.jpg" class="d-block w-100 img-in-carousel" alt="...">
            </div>
            <div class="carousel-item ">
                <img src="../static/images/4.jpg" class="d-block w-100 img-in-carousel" alt="...">
            </div>
            <div class="carousel-item">
                <img src="../static/images/5.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="../static/images/6.jpg" class="d-block w-100 img-in-carousel" alt="...">
            </div>
            <div class="carousel-item">
                <img src="../static/images/7.jpg" class="d-block w-100 img-in-carousel" alt="...">
            </div>
            <div class="carousel-item">
                <img src="../static/images/9.jpg" class="d-block w-100 img-in-carousel" alt="...">
            </div> -->
        </div>
        <!-- <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button> -->
    </div>
</div>
{% endblock %}

{% block project_datas %}
    {% for data in project_datas %}
        <p class="m-1 ms-2" shopid="{{data[0]}}" projectcode="{{data[1]}}" onclick="assignShop(this)">{{data[2]}} _&_ {{data[1]}}</p>
    {% endfor %}
{% endblock %}